SCREEN_TITLE = "Space Invaders"


SHIP_CHOSEN_SCALE = 1.3
SHIP_SCALE = 1
COLOR_CHOSEN_SCALE = 2
COLOR_SCALE = 1.5

COMMON_LASER_SPEED = 7
COMMON_LASER_DAMAGE = 1

RICHOCHET_LASER_SPEED = 10
RICHOCHET_LASER_DAMAGE = 1.5
RICHOCHET_ROTATION_SPEED = 10

PENETRATE_LASER_SPEED = 1
PENETRATE_LASER_DAMAGE = 0.05
PENETRATE_PULSE_SPEED = 0.01

HORMING_LASER_SPEED = 3
HORMING_LASER_DAMAGE = 1

ENEMY_SHOOTING_TIMER = 5
ENEMY_SPEED = 1